#pragma once

#include "config_common.h"

#define SOLENOID_PIN D2
#define SOLENOID_DEFAULT_DWELL 10
#define SOLENOID_MIN_DWELL 1
#define SOLENOID_MAX_DWELL 100
#define SOLENOID_BUZZ_ACTUATED 10
#define SOLENOID_BUZZ_NONACTUATED 10
#define SOLENOID_DWELL_STEP_SIZE 1

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF