#include QMK_KEYBOARD_H
#include <stdio.h>

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_60_ansi_split_bs_rshift(KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_DEL, KC_BSPC, 
                                             KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, 
                                             KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, 
                                             KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, MO(2), 
                                             KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,                         KC_RALT, KC_RGUI, KC_RCTL, MO(1)),
        [1] = LAYOUT_60_ansi_split_bs_rshift(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_TRNS, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, MO(3), 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                                         KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS),
        [2] = LAYOUT_60_ansi_split_bs_rshift(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_PGUP, KC_TRNS, KC_TRNS, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDN, KC_END, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
                                             KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3)),
        [3] = LAYOUT_60_ansi_split_bs_rshift(RESET, KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_F18, KC_F19, KC_F20, KC_F21, KC_F22, KC_F23, KC_F24, KC_NO, KC_NO, 
                                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLU, KC_NO, KC_TRNS, 
                                             OSL(4), KC_NO, KC_NO, KC_MPLY,                                KC_MPRV, KC_VOLD, KC_MNXT, KC_TRNS),
        [4] = LAYOUT_60_ansi_split_bs_rshift(KC_NO, UC(0x3A9), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, 
                                             KC_TRNS, KC_NO, KC_NO, KC_NO,                                    KC_NO, KC_NO, KC_NO, KC_TRNS) 											 
};

#ifdef OLED_DRIVER_ENABLE
static char wpm_str[32];

static const char PROGMEM bottom_bar[] = {
0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x00
};

static const char PROGMEM led_off[] = {0xA0, 0x00};
static const char PROGMEM led_on[] = {0xA1, 0x00};
static const char PROGMEM progbar[] = {0x82, 0x00};

void oled_task_user(void) {
    // Host Keyboard LED Status
    led_t led_state = host_keyboard_led_state();
    oled_write_P(PSTR("CAP "), false);
    led_state.caps_lock ? oled_write_P(led_on, false) : oled_write_P(led_off, false);
    oled_write_P(PSTR("   "), false);
    oled_write_P(PSTR("NUM "), false);
    led_state.num_lock ? oled_write_P(led_on, false) : oled_write_P(led_off, false);
    oled_write_P(PSTR("   "), false);
    oled_write_P(PSTR("SCR "), false);
    led_state.scroll_lock ? oled_write_P(led_on, false) : oled_write_P(led_off, false);
    oled_write_P(bottom_bar, false);

    // Host Keyboard Layer Status
    oled_write_P(PSTR("LAYER: "), false);

    switch (get_highest_layer(layer_state)) {
        case 0:
            oled_write_P(PSTR("QWERTY\n"), false);
            break;
        case 1:
            oled_write_P(PSTR("LOWER NAV\n"), false);
            break;
        case 2:
            oled_write_P(PSTR("UPPER NAV\n"), false);
            break;
        case 3:
            oled_write_P(PSTR("MEDIA\n"), false);
            break;
		case 4:
            oled_write_P(PSTR("UNICODE\n"), false);
            break;
        default:
            // Or use the write_ln shortcut over adding '\n' to the end of your string
            oled_write_ln_P(PSTR("UNDEFINED"), false);
    }

    uint8_t current_wpm = get_current_wpm();
    uint8_t wpm_bar_p = current_wpm / 10;
    int wpm_str_len = sprintf(wpm_str, "%u", current_wpm);
    for (int i = 0; i < (21 - wpm_str_len); i++)
    {
        if (i < wpm_bar_p) 
        {
           oled_write_P(progbar, false);
        }
        else
        {
           oled_write_P(PSTR(" "), false);
        }      
    }
    oled_write(wpm_str, false);
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) { return OLED_ROTATION_180; };
#endif